### ISSUE TITLE
Save causes error. 

### ISSUE THREAD

**Issue by rafstahelin** [Zyin055/Config-Presets#63]
Anybody know how to avoid this error? On latest webui version. Is there a conflict?

[Config-Presets] Changed to: SDXL --- 1024x1024
Traceback (most recent call last):
  File "D:\auto1111 SDXL\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\auto1111 SDXL\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\auto1111 SDXL\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\auto1111 SDXL\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\auto1111 SDXL\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\auto1111 SDXL\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\auto1111 SDXL\stable-diffusion-webui\extensions\Config-Presets\scripts\config_presets.py", line 1138, in func
    new_setting_map[component_id] = modules.sd_samplers.samplers_map[new_value.lower()]
AttributeError: 'int' object has no attribute 'lower'

**Comment by Zyin055** [comment]
I cannot replicate your error on A1111 1.6.0 or the latest commit (as of 9/7/23). Can you provide more information that may help?

The error is complaining that a sampler is a number/index instead of a string.

**Comment by rafstahelin** [comment]
i just add a new preset 
![chrome_MU0dfSTfQ1](https://github.com/Zyin055/Config-Presets/assets/64715158/49d700d8-9d86-4016-9c07-d71e67531948)
![chrome_fXoKluWyKq](https://github.com/Zyin055/Config-Presets/assets/64715158/c2b30a77-516d-4c37-a6d6-39e83ddc6b2f)
Attached the error screengrab and my extensions. Assuming it is a conflict with another extension

**Comment by Jimmni** [comment]
Same for me. Automatic1111 v1.6.0, any attempt to save just throws up errors and nothing gets saved.

**Comment by killakrust** [comment]
Getting the same error myself. I've tried disabling all other extensions to see if there was a clash, but no luck.

Not sure if this helps, but the error returned is show below:
![image](https://github.com/Zyin055/Config-Presets/assets/18518364/0e23cec1-62c2-4dd5-a4a8-2549a56f5969)

Would love to see this fixed, as this extension saves so much time when I'm using A1111. Love it.

**Comment by Zyin055** [comment]
I finally managed to replicate this error in my Automatic1111 1.5 installation (the fix works for both A1111 1.5 and 1.6.0). Since I was able to reproduce it the error on my end, I was able to make a fix for it.

@rafstahelin @Jimmni @killakrust Please update your Config Presets extension and see if the issue is resolved for you.

**Comment by ENTPRESTIGIOUS** [comment]
Check new commit guys!
