### ISSUE TITLE
[Bug] Extensions do not work.

### ISSUE THREAD

**Issue by re-unknown** [Zyin055/Config-Presets#7]
I installed from the Extensions tab and got the following error, it still occurs after restarting.

```
Applying xformers cross attention optimization.
Model loaded.
[ERROR] Config Presets: Could not find config file at '/home/ubuntu-wsl2/git/stable-diffusion-webui/extensions/Config-Presets\config.json'. The Config Presets dropdown will not work!
Error running after_component: /home/ubuntu-wsl2/git/stable-diffusion-webui/extensions/Config-Presets/scripts/config_presets.py
Traceback (most recent call last):
  File "/home/ubuntu-wsl2/git/stable-diffusion-webui/modules/scripts.py", line 381, in after_component
    script.after_component(component, **kwargs)
  File "/home/ubuntu-wsl2/git/stable-diffusion-webui/extensions/Config-Presets/scripts/config_presets.py", line 59, in after_component
    for k in self.config_presets:
AttributeError: 'Script' object has no attribute 'config_presets'

[ERROR] Config Presets: Could not find config file at '/home/ubuntu-wsl2/git/stable-diffusion-webui/extensions/Config-Presets\config.json'. The Config Presets dropdown will not work!
Error running after_component: /home/ubuntu-wsl2/git/stable-diffusion-webui/extensions/Config-Presets/scripts/config_presets.py
Traceback (most recent call last):
  File "/home/ubuntu-wsl2/git/stable-diffusion-webui/modules/scripts.py", line 381, in after_component
    script.after_component(component, **kwargs)
  File "/home/ubuntu-wsl2/git/stable-diffusion-webui/extensions/Config-Presets/scripts/config_presets.py", line 59, in after_component
    for k in self.config_presets:
AttributeError: 'Script' object has no attribute 'config_presets'

Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860
```
It is possible that other extensions are conflicting, but I am reporting it anyway. It is obvious that it is an excellent extension and we would love to use it ❤.

**Comment by Outsiderj** [comment]
Not working for me either.

**Comment by Zyin055** [comment]
Try uninstalling then update to the newest version. This may have been a linux only issue with file paths.

Post here if the fix works since I don't have a linux machine to test it.

**Comment by re-unknown** [comment]
![image](https://user-images.githubusercontent.com/51767262/207952504-61b0fff1-d6dc-4e60-9fe0-e53b8069f334.png)
Looks like the path issue was successfully fixed, thanks for the great job!

**Comment by Zyin055** [comment]
> Looks like the path issue was successfully fixed, thanks for the great job!

Based on the screenshot it looks like you're not using an English localization, which I don't think works. Does it work as expected for you?

**Comment by re-unknown** [comment]
Yes, I am using Japanese and it works normally.
I don't use Japanese in config.json so I don't know the details, but the UI is fine in Japanese.
