### ISSUE TITLE
[BUG] I get ERROR icons when saving sometimes AUTOMATIC1111 v1.7.0

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [Zyin055/Config-Presets#75]
I am using Stable Diffusion 1.7 and sometimes, I have trouble saving my presets because it gives me an ERROR sign. It's very inconsistent and if it could be fixed, that'd be great.

**Comment by Zyin055** [comment]
> Stable Diffusion 1.7

There is no such thing as Stable Diffusion 1.7. Do you mean A1111 1.7.0?

> I have trouble saving my presets because it gives me an ERROR sign.

I can't help when your description is that vague and don't even post what the error was.

**Comment by ENTPRESTIGIOUS** [comment]
> There is no such thing as Stable Diffusion 1.7. Do you mean A1111 1.7.0?

Yes, my bad.

> I can't help when your description is that vague and don't even post what the error was.

Basically, I have generated something and I want to save it using Config Presets. I go to the Add/Remove section and it gives me a bunch of buttons to check what I want to save. Having chosen my options, I try to save it but it gives me an ERROR symbol and doesn't save to the JSON file. I'll try to provide logs later on if I can.

**Comment by ENTPRESTIGIOUS** [comment]
It's actually similar to their issue but I think they're using AUTOMATIC1111 v1.6.0
https://github.com/Zyin055/Config-Presets/issues/63

**Comment by ENTPRESTIGIOUS** [comment]
```
Traceback (most recent call last):
  File "D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\extensions\Config-Presets\scripts\config_presets.py", line 1213, in func
    new_setting_map[component_id] = modules.sd_samplers.samplers_map[new_value.lower()]
KeyError: 'use same sampler'
```

**Comment by Zyin055** [comment]
I think I know what the issue is. Are you trying to save `hr_sampler` when it is set to "Use same sampler"? If so, I'll work on a fix for that edge case.

**Comment by Zyin055** [comment]
@ENTPRESTIGIOUS I pushed an update that should fix this issue, try updating and see if the problem is resolved.

**Comment by ENTPRESTIGIOUS** [comment]
> @ENTPRESTIGIOUS I pushed an update that should fix this issue, try updating and see if the problem is resolved.

Will do!

**Comment by ENTPRESTIGIOUS** [comment]
Seems to be working for now, I'll reopen if any issue persists! Thank you for the patch!

**Comment by ENTPRESTIGIOUS** [comment]
> I think I know what the issue is. Are you trying to save `hr_sampler` when it is set to "Use same sampler"? If so, I'll work on a fix for that edge case.

I think that could be why...
