### ISSUE TITLE
Component with id 2096 not a valid input component.

### ISSUE THREAD

**Issue by AllInOneMighty** [Zyin055/Config-Presets#79]
When I try to load any config preset in the `img2img` tab, including "None", I get this error message every time:

```
Traceback (most recent call last):
  File "S:\Install\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\Install\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "S:\Install\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1233, in preprocess_data
    assert isinstance(
AssertionError: <class 'gradio.layouts.Accordion'> Component with id 2096 not a valid input component.
```

I tried to remove all settings from `config-img2img.json` except "None", and even if I do, selecting "None" still generates this error.

My `config-img2img-custom-tracked-components.txt`:
```
# Put custom img2img tracked component IDs here. This will allow those fields to be saved as a config preset.
# Lines starting with a # are ignored.
# Component IDs can be found in the HTML (id="..."), in modules/ui.py (elem_id="..."), or in an extensions python code. IDs like "component-5890" won't work because the number at the end will change each startup.
# Entering an invalid component ID here will cause this extension to error and not load. Components that do not have a value associated with them, such as tabs and accordions, are not supported.
# Note that components on the top row of the UI cannot be added here, such as "setting_sd_model_checkpoint", "setting_sd_vae", and "setting_CLIP_stop_at_last_layers".

# Other fields:
#img2img_prompt
#img2img_neg_prompt
#img2img_mask_mode
#img2img_mask_blur
#img2img_mask_alpha
#img2img_inpainting_fill
#img2img_inpaint_full_res
#img2img_inpaint_full_res_padding
#resize_mode
img2img_scale
#img2img_seed
#img2img_subseed_show
#img2img_subseed
#img2img_subseed_strength
#img2img_seed_resize_from_w
#img2img_seed_resize_from_h
#img2img_tiling
#img2img_batch_input_dir
#img2img_batch_output_dir
#img2img_batch_inpaint_mask_dir

# Script dropdown:
#script_list

# X/Y/Z plot (script):
#script_img2img_xyz_plot_x_type
#script_img2img_xyz_plot_y_type
#script_img2img_xyz_plot_z_type
#script_img2img_xyz_plot_x_values
#script_img2img_xyz_plot_y_values
#script_img2img_xyz_plot_z_values

# Loopback (script):
#script_loopback_loops
#script_loopback_final_denoising_strength

# SD upscale (script):
#script_sd_upscale_overlap
#script_sd_upscale_scale_factor
#script_sd_upscale_upscaler_index

# Latent Couple (extension):
#cd_img2img_divisions
#cd_img2img_positions
#cd_img2img_weights
#cd_img2img_end_at_this_step

# ControlNet (extension):
img2img_controlnet_ControlNet-0_controlnet_enable_checkbox
#img2img_controlnet_ControlNet-0_controlnet_low_vram_checkbox
img2img_controlnet_ControlNet-0_controlnet_pixel_perfect_checkbox
#img2img_controlnet_ControlNet-0_controlnet_preprocessor_preview_checkbox
img2img_controlnet_ControlNet-0_controlnet_type_filter_radio
img2img_controlnet_ControlNet-0_controlnet_preprocessor_dropdown
img2img_controlnet_ControlNet-0_controlnet_model_dropdown
img2img_controlnet_ControlNet-0_controlnet_control_weight_slider
img2img_controlnet_ControlNet-0_controlnet_start_control_step_slider
img2img_controlnet_ControlNet-0_controlnet_ending_control_step_slider
img2img_controlnet_ControlNet-0_controlnet_control_mode_radio
#img2img_controlnet_ControlNet-0_controlnet_resize_mode_radio
#img2img_controlnet_ControlNet-0_controlnet_automatically_send_generated_images_checkbox

#img2img_controlnet_ControlNet-1_controlnet_enable_checkbox
#img2img_controlnet_ControlNet-1_controlnet_low_vram_checkbox
#img2img_controlnet_ControlNet-1_controlnet_pixel_perfect_checkbox
#img2img_controlnet_ControlNet-1_controlnet_preprocessor_preview_checkbox
#img2img_controlnet_ControlNet-1_controlnet_preprocessor_dropdown
#img2img_controlnet_ControlNet-1_controlnet_model_dropdown
#img2img_controlnet_ControlNet-1_controlnet_control_weight_slider
#img2img_controlnet_ControlNet-1_controlnet_start_control_step_slider
#img2img_controlnet_ControlNet-1_controlnet_ending_control_step_slider
#img2img_controlnet_ControlNet-1_controlnet_control_mode_radio
#img2img_controlnet_ControlNet-1_controlnet_resize_mode_radio
#img2img_controlnet_ControlNet-1_controlnet_automatically_send_generated_images_checkbox

#img2img_controlnet_ControlNet-2_controlnet_enable_checkbox
#img2img_controlnet_ControlNet-2_controlnet_low_vram_checkbox
#img2img_controlnet_ControlNet-2_controlnet_pixel_perfect_checkbox
#img2img_controlnet_ControlNet-2_controlnet_preprocessor_preview_checkbox
#img2img_controlnet_ControlNet-2_controlnet_preprocessor_dropdown
#img2img_controlnet_ControlNet-2_controlnet_model_dropdown
#img2img_controlnet_ControlNet-2_controlnet_control_weight_slider
#img2img_controlnet_ControlNet-2_controlnet_start_control_step_slider
#img2img_controlnet_ControlNet-2_controlnet_ending_control_step_slider
#img2img_controlnet_ControlNet-2_controlnet_control_mode_radio
#img2img_controlnet_ControlNet-2_controlnet_resize_mode_radio
#img2img_controlnet_ControlNet-2_controlnet_automatically_send_generated_images_checkbox

# Tiled Diffusion (extension)
MD-i2i-enabled
MD-i2i-keep-input-size
MD-i2i-method
#MD-i2i-control-tensor-cpu
MD-i2i-latent-tile-width
MD-i2i-latent-tile-height
MD-i2i-latent-tile-overlap
MD-i2i-latent-tile-batch-size
MD-i2i-upscaler-index
MD-i2i-upscaler-factor
# Tiled Diffusion - Noise Inversion
MD-i2i-noise-inverse
MD-i2i-noise-inverse-steps
MD-i2i-noise-inverse-retouch
MD-i2i-noise-inverse-renoise-strength
#MD-i2i-noise-inverse-renoise-kernel
# Tiled Diffusion - Region Prompt Control
#MD-i2i-enable-bbox-control
#MD-i2i-draw-background
#MD-i2i-cfg-name
# Tiled Diffusion - Region Prompt Control - Region 1
#MD-bbox-i2i-0-enable
#MD-i2i-0-blend-mode
#MD-i2i-0-feather
#MD-i2i-0-x
#MD-i2i-0-y
#MD-i2i-0-w
#MD-i2i-0-h
#MD-i2i-0-prompt
#MD-i2i-0-neg-prompt
#MD-i2i-0-seed
# Tiled Diffusion - Region Prompt Control - Region 2
#MD-bbox-i2i-1-enable
#MD-i2i-1-blend-mode
#MD-i2i-1-feather
#MD-i2i-1-x
#MD-i2i-1-y
#MD-i2i-1-w
#MD-i2i-1-h
#MD-i2i-1-prompt
#MD-i2i-1-neg-prompt
#MD-i2i-1-seed
# Tiled Diffusion - Region Prompt Control - Region 3
#MD-bbox-i2i-2-enable
#MD-i2i-2-blend-mode
#MD-i2i-2-feather
#MD-i2i-2-x
#MD-i2i-2-y
#MD-i2i-2-w
#MD-i2i-2-h
#MD-i2i-2-prompt
#MD-i2i-2-neg-prompt
#MD-i2i-2-seed
# Tiled Diffusion - Tiled VAE
MDV-i2i-enabled
MD-i2i-vae2gpu
MD-i2i-enc-size
MD-i2i-dec-size
MD-i2i-fastenc
MD-i2i-fastenc-colorfix
MD-i2i-fastdec

# StableSR (extension)
#SR Model does not have an ID as of June 1 2023
#StableSR-scale
#StableSR-color-fix
#StableSR-save-original
#StableSR-pure-noise

# ADetailer (extension)
#script_img2img_adetailer_ad_enable
# ADetailer - 1st tab
#script_img2img_adetailer_ad_model
#script_img2img_adetailer_ad_prompt
#script_img2img_adetailer_ad_negative_prompt
# ADetailer - 1st tab - Detection
#script_img2img_adetailer_ad_confidence
#script_img2img_adetailer_ad_mask_min_ratio
#script_img2img_adetailer_ad_mask_max_ratio
# ADetailer - 1st tab - Mask Preprocessing
#script_img2img_adetailer_ad_x_offset
#script_img2img_adetailer_ad_y_offset
#script_img2img_adetailer_ad_dilate_erode
#script_img2img_adetailer_ad_mask_merge_invert
# ADetailer - 1st tab - Inpainting
#script_img2img_adetailer_ad_mask_blur
#script_img2img_adetailer_ad_denoising_strength
#script_img2img_adetailer_ad_inpaint_full_res
#script_img2img_adetailer_ad_inpaint_full_res_padding
#script_img2img_adetailer_ad_use_inpaint_width_height
#script_img2img_adetailer_ad_inpaint_width
#script_img2img_adetailer_ad_inpaint_height
#script_img2img_adetailer_ad_use_steps
#script_img2img_adetailer_ad_steps
#script_img2img_adetailer_ad_use_cfg_scale
#script_img2img_adetailer_ad_cfg_scale
#script_img2img_adetailer_ad_restore_face
# ADetailer - 1st tab - ControlNet
#script_img2img_adetailer_ad_controlnet_model
#script_img2img_adetailer_ad_controlnet_weight
#script_img2img_adetailer_ad_controlnet_guidance_start
#script_img2img_adetailer_ad_controlnet_guidance_end
# ADetailer - 2nd tab
#script_img2img_adetailer_ad_model_2nd
#script_img2img_adetailer_ad_prompt_2nd
#script_img2img_adetailer_ad_negative_prompt_2nd
# ADetailer - 2nd tab - Detection
#script_img2img_adetailer_ad_confidence_2nd
#script_img2img_adetailer_ad_mask_min_ratio_2nd
#script_img2img_adetailer_ad_mask_max_ratio_2nd
# ADetailer - 2nd tab - Mask Preprocessing
#script_img2img_adetailer_ad_x_offset_2nd
#script_img2img_adetailer_ad_y_offset_2nd
#script_img2img_adetailer_ad_dilate_erode_2nd
#script_img2img_adetailer_ad_mask_merge_invert_2nd
# ADetailer - 2nd tab - Inpainting
#script_img2img_adetailer_ad_mask_blur_2nd
#script_img2img_adetailer_ad_denoising_strength_2nd
#script_img2img_adetailer_ad_inpaint_full_res_2nd
#script_img2img_adetailer_ad_inpaint_full_res_padding_2nd
#script_img2img_adetailer_ad_use_inpaint_width_height_2nd
#script_img2img_adetailer_ad_inpaint_width_2nd
#script_img2img_adetailer_ad_inpaint_height_2nd
#script_img2img_adetailer_ad_use_steps_2nd
#script_img2img_adetailer_ad_steps_2nd
#script_img2img_adetailer_ad_use_cfg_scale_2nd
#script_img2img_adetailer_ad_cfg_scale_2nd
#script_img2img_adetailer_ad_restore_face_2nd
# ADetailer - 2nd tab - ADetailer ControlNet
#script_img2img_adetailer_ad_controlnet_model_2nd
#script_img2img_adetailer_ad_controlnet_weight_2nd
#script_img2img_adetailer_ad_controlnet_guidance_start_2nd
#script_img2img_adetailer_ad_controlnet_guidance_end_2nd

# Ultimate SD Upscale
#ultimateupscale_target_size_type
#ultimateupscale_custom_width
#ultimateupscale_custom_height
#ultimateupscale_custom_scale
#ultimateupscale_upscaler_index
#ultimateupscale_redraw_mode
#ultimateupscale_tile_width
#ultimateupscale_tile_height
#ultimateupscale_mask_blur
#ultimateupscale_padding
#ultimateupscale_seams_fix_type
#ultimateupscale_seams_fix_denoise
#ultimateupscale_seams_fix_width
#ultimateupscale_seams_fix_mask_blur
#ultimateupscale_seams_fix_padding
#ultimateupscale_save_upscaled_image
#ultimateupscale_save_seams_fix_image
```

Unfortunately, the error is pretty vague, so I could not find where in the code of `Config-Presets` this fails.

**Comment by AllInOneMighty** [comment]
Figured this out. The authors of the MutiDiffusion upscaler for Automatic1111 changed the "enable" checkboxes to accordions, making this setting impossible to set in ConfigPresets.

Filed an issue with the relevant extension here: https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/379
